# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 207dee2227e7db54bb16b2dfb1ef0920c7c89e893aedf472e6b40c82171884e3893784e04f4a79e61eeb9e2f88401ecd076f4e44896cc711198d42ee79d84d19

test:
  secret_key_base: b165704c6dc301884824664d6313c4aae8d722f7498df2fc6d4c05dc28cc7b578d2082e076c90db91b1273f0ec606e90098d676a3f66f7001cdbef1a34c8d9da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
